### ISSUE TITLE
Maintaining Apps

### ISSUE THREAD

**Issue by jag1g13** [PEDASI/PEDASI#21]
(Same applies to data sources)

How will we persuade App developers to keep their objects up to date?

- Needs to be made clear that app developers are responsible for making sure their apps are kept up to date
- Have 'report as broken' button on app page
  - This sends email to developer to ask them to investigate
  - If a few (how many?) people press this - hide the app until fixed
- Heartbeat?
  - Ping the app every now and then to check it still exists

**Comment by steve-crouch** [comment]
I think we can close this now, since we're no longer directly involved in the project. Can always reopen later if the situation changes.
